### ISSUE TITLE
Back-end shifting to Django

### ISSUE THREAD

**Issue by JINDALG** [Small-Start/myresume#12]
Original back-end is on Parse but it is outdated. So New back-end will be on Django.

**Comment by aayusharora** [comment]
@JINDALG , Please break it in small issues , 
1. Making Database
1.Maintain a google doc for clearing the end points provided be Restapi's .
2. Making Restapi's
Also break the above three according to the your need .

**Comment by JINDALG** [comment]
@aayusharora  Google Docs for Api documentation is ready .
[https://docs.google.com/document/d/1JGKP--ybNL6q0yLEqrxEkdSND5Jxl-HwVnZsXQ6rSac/edit?usp=sharing]

**Comment by aayusharora** [comment]
Thanks @JINDALG, good work.
