### ISSUE TITLE
Removing Unnecessary folders

### ISSUE THREAD

**Issue by aayusharora** [Small-Start/myresume#19]
We have a folder myresume, after the last merge of PR by @JINDALG, we have another myresume folder inside myresume . Please clear this out .

**Comment by JINDALG** [comment]
Inner myresume is the django version and all other is php version. I setup the whole thing together because time to time we move some html and js/css file in django version

**Comment by JINDALG** [comment]
We can change the name of inner myresume

**Comment by JINDALG** [comment]
myresume in paralell of js/css folder is django version and myresume inside myresume is setup folder required for django..

**Comment by aayusharora** [comment]
Ok got it, You can remove the Parse or php bindings as the branch will not effect master

**Comment by JINDALG** [comment]
will remove unnecessary file time to time/step by step

**Comment by JINDALG** [comment]
some files are removed.
