### ISSUE TITLE
on runing server showing syntax error

### ISSUE THREAD

**Issue by dreamerHarshit** [Small-Start/myresume#24]
/myresume/myresume/user_profile/models.py", line 11
    user = models.OneToOneField(User)
       ^
SyntaxError: invalid syntax

**Comment by JINDALG** [comment]
It is syntax of very old commit. May be you have not done migrations.
Kindly upload full traceback of Error.

**Comment by dreamerHarshit** [comment]
![error](https://cloud.githubusercontent.com/assets/13063679/16990423/9387b75a-4eb5-11e6-9612-66588970d3d2.png)

i have already tried python manage.py migrate.

**Comment by aayusharora** [comment]
@JINDALG  Can you please check this on your local.
Please update readme if something is not there.

**Comment by JINDALG** [comment]
resolved
